# Generated by Django 4.2 on 2023-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tutor', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=50)),
                ('Price_dollars', models.IntegerField()),
                ('Price_naira', models.IntegerField()),
                ('No_of_lessons', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
    ]
