# Generated by Django 4.2 on 2023-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Image',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
