# Generated by Django 4.2 on 2023-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'courses'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='Rating',
            field=models.IntegerField(),
        ),
    ]
