# Generated by Django 4.2 on 2023-05-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_description',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
