# Generated by Django 4.2 on 2023-05-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_content',
            field=models.TextField(blank=True, help_text='separate each content by a comma', null=True),
        ),
    ]
