# Generated by Django 4.2 on 2023-05-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Review'},
        ),
    ]
