# Generated by Django 4.2 on 2023-05-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Review'},
        ),
    ]
