# Generated by Django 4.2 on 2023-06-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
