# Generated by Django 4.2 on 2023-06-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_userwallet_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
